//Test code generated by ISTA

public class hierarchyTester_RT{

	private hierarchy hierarchy;
	
	protected void setUp()  throws Exception {
		hierarchy = new hierarchy();
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		setUp();
		hierarchy.T4();
		assert hierarchy.P6() : "1_1";
		assert hierarchy.P5() : "1_1";
		hierarchy.T10();
		assert hierarchy.P5() : "1_1_1";
		assert hierarchy.P10() : "1_1_1";
		hierarchy.T11();
		assert hierarchy.P5() : "1_1_1_1";
		assert hierarchy.P8() : "1_1_1_1";
		hierarchy.T5();
		assert hierarchy.P8() : "1_1_1_1_1";
		assert hierarchy.P7() : "1_1_1_1_1";
		hierarchy.T7();
		assert hierarchy.P2() : "1_1_1_1_1_1";
		hierarchy.T2();
		assert hierarchy.P3() : "";
		hierarchy.T3();
		assert hierarchy.P1() : "";
	}

	public void test2() throws Exception {
		System.out.println("Test case 2");
		setUp();
		hierarchy.T4();
		hierarchy.T10();
		hierarchy.T5();
		assert hierarchy.P7() : "1_1_1_2";
		assert hierarchy.P10() : "1_1_1_2";
		hierarchy.T11();
		assert hierarchy.P8() : "1_1_1_2_1";
		assert hierarchy.P7() : "1_1_1_2_1";
	}

	public void test3() throws Exception {
		System.out.println("Test case 3");
		setUp();
		hierarchy.T4();
		hierarchy.T12();
		assert hierarchy.P5() : "1_1_2";
		assert hierarchy.P11() : "1_1_2";
		hierarchy.T13();
		assert hierarchy.P5() : "1_1_2_1";
		assert hierarchy.P8() : "1_1_2_1";
	}

	public void test4() throws Exception {
		System.out.println("Test case 4");
		setUp();
		hierarchy.T4();
		hierarchy.T12();
		hierarchy.T5();
		assert hierarchy.P7() : "1_1_2_2";
		assert hierarchy.P11() : "1_1_2_2";
		hierarchy.T13();
		assert hierarchy.P8() : "1_1_2_2_1";
		assert hierarchy.P7() : "1_1_2_2_1";
	}

	public void test5() throws Exception {
		System.out.println("Test case 5");
		setUp();
		hierarchy.T4();
		hierarchy.T5();
		assert hierarchy.P6() : "1_1_3";
		assert hierarchy.P7() : "1_1_3";
		hierarchy.T10();
		assert hierarchy.P7() : "1_1_3_1";
		assert hierarchy.P10() : "1_1_3_1";
	}

	public void test6() throws Exception {
		System.out.println("Test case 6");
		setUp();
		hierarchy.T4();
		hierarchy.T5();
		hierarchy.T12();
		assert hierarchy.P7() : "1_1_3_2";
		assert hierarchy.P11() : "1_1_3_2";
	}

	public void testAll() throws Exception {
		test1();
		test2();
		test3();
		test4();
		test5();
		test6();
	}

	public static void main(String[] args) throws Exception {
		 new hierarchyTester_RT().testAll();
	}

}
