//Test code generated by ISTA

public class BankAccountTester_GC{

	private BankAccount bankaccount;
	
	protected void setUp()  throws Exception {
		bankaccount = new BankAccount();
		bankaccount.deposit(100);
	}
	
	public void test1_1_1() throws Exception {
		System.out.println("Test case 1_1_1");
		setUp();
		withdraw(300);
		assert getBalance()==-200 : "Test failed at 1_1";
		assert !bankaccount.getClosed() && bankaccount.getBalance()<0 && banaccount.getBalance()>=-1000 : "Test failed at 1_1";
	}

	public void testAll() throws Exception {
		test1_1_1();
	}


	private static final int NEGATIVE = -500;
	
	
	
	public static void main(String[] args) throws Exception {
		 new BankAccountTester_GC().testAll();
	}

}
