//Test code generated by FAST

public class seniorBuyerRoleForSaleTester_RT{

	protected void setUp()  throws Exception {
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		setUp();
		bid(S1, C1);
		assert sale(S1, C1) : "Test failed at 1_1";
		assert sale(S2, C2) : "Test failed at 1_1";
	}

	public void test2() throws Exception {
		System.out.println("Test case 2");
		setUp();
		bid(S2, C2);
		assert sale(S1, C1) : "Test failed at 1_2";
		assert sale(S2, C2) : "Test failed at 1_2";
	}

	public void test3() throws Exception {
		System.out.println("Test case 3");
		setUp();
		consult(S1, C1);
		assert sale(S1, C1) : "Test failed at 1_3";
		assert sale(S2, C2) : "Test failed at 1_3";
	}

	public void test4() throws Exception {
		System.out.println("Test case 4");
		setUp();
		consult(S2, C2);
		assert sale(S1, C1) : "Test failed at 1_4";
		assert sale(S2, C2) : "Test failed at 1_4";
	}

	public void testAll() throws Exception {
		test1();
		test2();
		test3();
		test4();
	}

	public static void main(String[] args) throws Exception {
		 new seniorBuyerRoleForSaleTester_RT().testAll();
	}

}
