//Test code generated by MISTA

package test;

import cruisecontrol.*;
import org.junit.*;
import static org.junit.Assert.*;

public class ControllerTester_RT {

	private Controller controller;
	
	@Before
	public void setUp()  throws Exception {
		controller = new Controller();
	}
	
	@Test
	public void test1() throws Exception {
		System.out.println("Test case 1");
		controller.engineOn();
		assertTrue("1_1", controller.getControlState()==Controller.ACTIVE);
		controller.engineOff();
		assertTrue("1_1_1", controller.getControlState()==Controller.INACTIVE);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
	}

	@Test
	public void test2() throws Exception {
		System.out.println("Test case 2");
		controller.engineOn();
		controller.accelerator();
		assertTrue("1_1_2", controller.getControlState()==Controller.ACTIVE);
	}

	@Test
	public void test3() throws Exception {
		System.out.println("Test case 3");
		controller.engineOn();
		controller.on();
		assertTrue("1_1_3", controller.getControlState()==Controller.CRUISING);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.ENABLED);
		controller.engineOff();
		assertTrue("1_1_3_1", controller.getControlState()==Controller.INACTIVE);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
	}

	@Test
	public void test4() throws Exception {
		System.out.println("Test case 4");
		controller.engineOn();
		controller.on();
		controller.accelerator();
		assertTrue("1_1_3_2", controller.getControlState()==Controller.STANDBY);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
		controller.engineOff();
		assertTrue("1_1_3_2_1", controller.getControlState()==Controller.INACTIVE);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
	}

	@Test
	public void test5() throws Exception {
		System.out.println("Test case 5");
		controller.engineOn();
		controller.on();
		controller.accelerator();
		controller.resume();
		assertTrue("1_1_3_2_2", controller.getControlState()==Controller.CRUISING);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.ENABLED);
	}

	@Test
	public void test6() throws Exception {
		System.out.println("Test case 6");
		controller.engineOn();
		controller.on();
		controller.accelerator();
		controller.on();
		assertTrue("1_1_3_2_3", controller.getControlState()==Controller.CRUISING);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.ENABLED);
	}

	@Test
	public void test7() throws Exception {
		System.out.println("Test case 7");
		controller.engineOn();
		controller.on();
		controller.brake();
		assertTrue("1_1_3_3", controller.getControlState()==Controller.STANDBY);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
	}

	@Test
	public void test8() throws Exception {
		System.out.println("Test case 8");
		controller.engineOn();
		controller.on();
		controller.off();
		assertTrue("1_1_3_4", controller.getControlState()==Controller.STANDBY);
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
	}

	@Test
	public void test9() throws Exception {
		System.out.println("Test case 9");
		controller.engineOn();
		controller.brake();
		assertTrue("1_1_4", controller.getControlState()==Controller.ACTIVE);
	}

}
