//Test code generated by MISTA

package test;

import vending.Coin;
import vending.VendingMachine;
import org.junit.*;
import static org.junit.Assert.*;

public class VendingMachineTester_SC_1 {

	private VendingMachine vendingmachine;
	
	@Before
	public void setUp()  throws Exception {
		vendingmachine = new VendingMachine();
		vendingmachine.setDrink(COFFEE, 35, 1);
		vendingmachine.setDrink(JUICE, 110, 1);
		vendingmachine.setDrink(SODA, 105, 1);
	}
	
	@Test
	public void test1() throws Exception {
		System.out.println("Test case 1");
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_1", vendingmachine.getDeposit()==10);
		assertTrue("1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1_1", vendingmachine.getDeposit()==110);
		assertTrue("1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_1", vendingmachine.getDeposit()==135);
		assertTrue("1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_1_1", vendingmachine.getDeposit()==140);
		assertTrue("1_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(SODA);
		assertTrue("1_1_1_1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_1_1", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==140-105);
	}

	@Test
	public void test2() throws Exception {
		System.out.println("Test case 2");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		assertTrue("1_1_1_1_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test3() throws Exception {
		System.out.println("Test case 3");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_1_1_1_3", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_1_3", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_1_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_1_3", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==140-35);
	}

	@Test
	public void test4() throws Exception {
		System.out.println("Test case 4");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(JUICE);
		assertTrue("1_1_1_1_1_4", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_1_4", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_1_1_4", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==140-110);
	}

	@Test
	public void test5() throws Exception {
		System.out.println("Test case 5");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(SODA);
		assertTrue("1_1_1_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_2", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==135-105);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_1_2_1", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_2_1", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test6() throws Exception {
		System.out.println("Test case 6");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		assertTrue("1_1_1_1_3", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_3", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_1_3_1", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_1_3_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_3_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test7() throws Exception {
		System.out.println("Test case 7");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_1_1_4", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_4", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_4", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==135-35);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_1_4_1", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_1_4_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_1_4_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test8() throws Exception {
		System.out.println("Test case 8");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(JUICE);
		assertTrue("1_1_1_1_5", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_1_5", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_5", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_1_5", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==135-110);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_1_5_1", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_1_5_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_1_5_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_1_5_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test9() throws Exception {
		System.out.println("Test case 9");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_2", vendingmachine.getDeposit()==115);
		assertTrue("1_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(SODA);
		assertTrue("1_1_1_2_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_1", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==115-105);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_2_1_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_1_1", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test10() throws Exception {
		System.out.println("Test case 10");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		assertTrue("1_1_1_2_2", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_2_2_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test11() throws Exception {
		System.out.println("Test case 11");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_1_2_3", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_2_3", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_2_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_3", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==115-35);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_2_3_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_2_3_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_2_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_2_3_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test12() throws Exception {
		System.out.println("Test case 12");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(JUICE);
		assertTrue("1_1_1_2_4", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_2_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_4", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_2_4", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==115-110);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_2_4_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_2_4_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_2_4_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_2_4_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test13() throws Exception {
		System.out.println("Test case 13");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(SODA);
		assertTrue("1_1_1_3", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_3", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==110-105);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_3_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_3_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_3_1", checkDrink(SODA, 105, 0));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_3_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_1_3_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_3_1_1", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test14() throws Exception {
		System.out.println("Test case 14");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(SODA);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_3_2", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_3_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_3_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_3_2", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test15() throws Exception {
		System.out.println("Test case 15");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		assertTrue("1_1_1_4", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_4", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_4_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_4_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_4_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_4_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_1_4_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_4_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_4_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test16() throws Exception {
		System.out.println("Test case 16");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_4_2", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_4_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_4_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_4_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test17() throws Exception {
		System.out.println("Test case 17");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_1_5", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_5", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_5", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_5", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==110-35);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_5_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_5_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_5_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_5_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_5_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_1_5_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_5_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_5_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test18() throws Exception {
		System.out.println("Test case 18");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(COFFEE);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_5_2", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_5_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_1_5_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_1_5_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test19() throws Exception {
		System.out.println("Test case 19");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(JUICE);
		assertTrue("1_1_1_6", vendingmachine.getDeposit()==0);
		assertTrue("1_1_1_6", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_6", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_6", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==110-110);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_1_6_1", vendingmachine.getDeposit()==25);
		assertTrue("1_1_1_6_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_6_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_6_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_6_1_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_1_6_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_6_1_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_6_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test20() throws Exception {
		System.out.println("Test case 20");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(JUICE);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_1_6_2", vendingmachine.getDeposit()==5);
		assertTrue("1_1_1_6_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_1_6_2", checkDrink(JUICE, 110, 0));
		assertTrue("1_1_1_6_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test21() throws Exception {
		System.out.println("Test case 21");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_2", vendingmachine.getDeposit()==35);
		assertTrue("1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_2_1", vendingmachine.getDeposit()==40);
		assertTrue("1_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_1_2_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1_2_1_1_1", vendingmachine.getDeposit()==100);
		assertTrue("1_1_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test22() throws Exception {
		System.out.println("Test case 22");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_2_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_1_2_1_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1_2", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==40-35);
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1_2_1_2_1", vendingmachine.getDeposit()==100);
		assertTrue("1_1_2_1_2_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_1_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test23() throws Exception {
		System.out.println("Test case 23");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		assertTrue("1_1_2_2", vendingmachine.getDeposit()==0);
		assertTrue("1_1_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1_2_2_1", vendingmachine.getDeposit()==100);
		assertTrue("1_1_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_2_2_1_1", vendingmachine.getDeposit()==105);
		assertTrue("1_1_2_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_2_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test24() throws Exception {
		System.out.println("Test case 24");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_2_2_2", vendingmachine.getDeposit()==5);
		assertTrue("1_1_2_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_2_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_2_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test25() throws Exception {
		System.out.println("Test case 25");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_1_2_3", vendingmachine.getDeposit()==0);
		assertTrue("1_1_2_3", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_3", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==35-35);
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1_2_3_1", vendingmachine.getDeposit()==100);
		assertTrue("1_1_2_3_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_3_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_2_3_1_1", vendingmachine.getDeposit()==105);
		assertTrue("1_1_2_3_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_3_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(SODA);
		assertTrue("", vendingmachine.getDeposit()==0);
		assertTrue("", checkDrink(COFFEE, 35, 0));
		assertTrue("", checkDrink(JUICE, 110, 1));
		assertTrue("", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==105-105);
	}

	@Test
	public void test26() throws Exception {
		System.out.println("Test case 26");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(COFFEE);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_2_3_2", vendingmachine.getDeposit()==5);
		assertTrue("1_1_2_3_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_1_2_3_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_2_3_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test27() throws Exception {
		System.out.println("Test case 27");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_3", vendingmachine.getDeposit()==15);
		assertTrue("1_1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_1_3_1", vendingmachine.getDeposit()==0);
		assertTrue("1_1_3_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1_3_1_1", vendingmachine.getDeposit()==100);
		assertTrue("1_1_3_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_3_1_1_1", vendingmachine.getDeposit()==125);
		assertTrue("1_1_3_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_3_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test28() throws Exception {
		System.out.println("Test case 28");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_3_1_2", vendingmachine.getDeposit()==25);
		assertTrue("1_1_3_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_3_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_3_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test29() throws Exception {
		System.out.println("Test case 29");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.returnCoins();
		assertTrue("1_1_4", vendingmachine.getDeposit()==0);
		assertTrue("1_1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_1_4_1", vendingmachine.getDeposit()==100);
		assertTrue("1_1_4_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_4_1_1", vendingmachine.getDeposit()==125);
		assertTrue("1_1_4_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_4_1_1_1", vendingmachine.getDeposit()==130);
		assertTrue("1_1_4_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test30() throws Exception {
		System.out.println("Test case 30");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_4_1_2", vendingmachine.getDeposit()==105);
		assertTrue("1_1_4_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test31() throws Exception {
		System.out.println("Test case 31");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_1_4_2", vendingmachine.getDeposit()==25);
		assertTrue("1_1_4_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_4_2_1", vendingmachine.getDeposit()==30);
		assertTrue("1_1_4_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test32() throws Exception {
		System.out.println("Test case 32");
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_1_4_3", vendingmachine.getDeposit()==5);
		assertTrue("1_1_4_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_1_4_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_1_4_3", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test33() throws Exception {
		System.out.println("Test case 33");
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_2", vendingmachine.getDeposit()==100);
		assertTrue("1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_1", vendingmachine.getDeposit()==125);
		assertTrue("1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_1", vendingmachine.getDeposit()==130);
		assertTrue("1_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(SODA);
		assertTrue("1_2_1_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_1", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==130-105);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_1_1_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_1_1", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test34() throws Exception {
		System.out.println("Test case 34");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		assertTrue("1_2_1_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_1_2_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test35() throws Exception {
		System.out.println("Test case 35");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_2_1_1_3", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_3", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_3", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==130-35);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_1_3_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_1_3_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_1_3_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test36() throws Exception {
		System.out.println("Test case 36");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(JUICE);
		assertTrue("1_2_1_1_4", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_4", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_1_4", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==130-110);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_1_4_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_1_4_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_1_4_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_1_4_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test37() throws Exception {
		System.out.println("Test case 37");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(SODA);
		assertTrue("1_2_1_2", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_2", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==125-105);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_2_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_2_1", checkDrink(SODA, 105, 0));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_2_1_1", vendingmachine.getDeposit()==15);
		assertTrue("1_2_1_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_2_1_1", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test38() throws Exception {
		System.out.println("Test case 38");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(SODA);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_2_2", vendingmachine.getDeposit()==5);
		assertTrue("1_2_1_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_2_2", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test39() throws Exception {
		System.out.println("Test case 39");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		assertTrue("1_2_1_3", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_3", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_3_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_3_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_3_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_3_1_1", vendingmachine.getDeposit()==15);
		assertTrue("1_2_1_3_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_3_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test40() throws Exception {
		System.out.println("Test case 40");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_3_2", vendingmachine.getDeposit()==5);
		assertTrue("1_2_1_3_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_3_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_3_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test41() throws Exception {
		System.out.println("Test case 41");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_2_1_4", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_4", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_4", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==125-35);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_4_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_4_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_4_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_4_1_1", vendingmachine.getDeposit()==15);
		assertTrue("1_2_1_4_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_4_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_4_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test42() throws Exception {
		System.out.println("Test case 42");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(COFFEE);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_4_2", vendingmachine.getDeposit()==5);
		assertTrue("1_2_1_4_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_1_4_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_1_4_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test43() throws Exception {
		System.out.println("Test case 43");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(JUICE);
		assertTrue("1_2_1_5", vendingmachine.getDeposit()==0);
		assertTrue("1_2_1_5", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_5", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_5", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==125-110);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_1_5_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_1_5_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_5_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_5_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_5_1_1", vendingmachine.getDeposit()==15);
		assertTrue("1_2_1_5_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_5_1_1", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_5_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test44() throws Exception {
		System.out.println("Test case 44");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.purchase(JUICE);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_1_5_2", vendingmachine.getDeposit()==5);
		assertTrue("1_2_1_5_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_1_5_2", checkDrink(JUICE, 110, 0));
		assertTrue("1_2_1_5_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test45() throws Exception {
		System.out.println("Test case 45");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_2", vendingmachine.getDeposit()==105);
		assertTrue("1_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.purchase(SODA);
		assertTrue("1_2_2_1", vendingmachine.getDeposit()==0);
		assertTrue("1_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_1", checkDrink(SODA, 105, 0));
		assertTrue("", vendingmachine.getChange()==105-105);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_2_1_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_1_1", checkDrink(SODA, 105, 0));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_2_1_1_1", vendingmachine.getDeposit()==35);
		assertTrue("1_2_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_1_1_1", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test46() throws Exception {
		System.out.println("Test case 46");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(SODA);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_2_1_2", vendingmachine.getDeposit()==25);
		assertTrue("1_2_2_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_1_2", checkDrink(SODA, 105, 0));
	}

	@Test
	public void test47() throws Exception {
		System.out.println("Test case 47");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		assertTrue("1_2_2_2", vendingmachine.getDeposit()==0);
		assertTrue("1_2_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_2_2_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_2_2_1_1", vendingmachine.getDeposit()==35);
		assertTrue("1_2_2_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_2_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test48() throws Exception {
		System.out.println("Test case 48");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_2_2_2", vendingmachine.getDeposit()==25);
		assertTrue("1_2_2_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_2_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_2_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test49() throws Exception {
		System.out.println("Test case 49");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_2_2_3", vendingmachine.getDeposit()==0);
		assertTrue("1_2_2_3", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_2_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_3", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==105-35);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_2_3_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_2_3_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_2_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_3_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_2_3_1_1", vendingmachine.getDeposit()==35);
		assertTrue("1_2_2_3_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_2_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_3_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test50() throws Exception {
		System.out.println("Test case 50");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.purchase(COFFEE);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_2_3_2", vendingmachine.getDeposit()==25);
		assertTrue("1_2_2_3_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_2_3_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_2_3_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test51() throws Exception {
		System.out.println("Test case 51");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		assertTrue("1_2_3", vendingmachine.getDeposit()==0);
		assertTrue("1_2_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_3_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_3_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_3_1_1", vendingmachine.getDeposit()==35);
		assertTrue("1_2_3_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_3_1_1_1", vendingmachine.getDeposit()==40);
		assertTrue("1_2_3_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test52() throws Exception {
		System.out.println("Test case 52");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_3_1_2", vendingmachine.getDeposit()==15);
		assertTrue("1_2_3_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test53() throws Exception {
		System.out.println("Test case 53");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_3_2", vendingmachine.getDeposit()==25);
		assertTrue("1_2_3_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_3_2_1", vendingmachine.getDeposit()==30);
		assertTrue("1_2_3_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test54() throws Exception {
		System.out.println("Test case 54");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_3_3", vendingmachine.getDeposit()==5);
		assertTrue("1_2_3_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_2_3_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_3_3", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test55() throws Exception {
		System.out.println("Test case 55");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(COFFEE);
		assertTrue("1_2_4", vendingmachine.getDeposit()==0);
		assertTrue("1_2_4", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4", checkDrink(SODA, 105, 1));
		assertTrue("", vendingmachine.getChange()==100-35);
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_2_4_1", vendingmachine.getDeposit()==10);
		assertTrue("1_2_4_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_4_1_1", vendingmachine.getDeposit()==35);
		assertTrue("1_2_4_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_4_1_1_1", vendingmachine.getDeposit()==40);
		assertTrue("1_2_4_1_1_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test56() throws Exception {
		System.out.println("Test case 56");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(COFFEE);
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_4_1_2", vendingmachine.getDeposit()==15);
		assertTrue("1_2_4_1_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test57() throws Exception {
		System.out.println("Test case 57");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(COFFEE);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_2_4_2", vendingmachine.getDeposit()==25);
		assertTrue("1_2_4_2", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_4_2_1", vendingmachine.getDeposit()==30);
		assertTrue("1_2_4_2_1", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test58() throws Exception {
		System.out.println("Test case 58");
		vendingmachine.insertCoin(Coin.DOLLAR);
		vendingmachine.purchase(COFFEE);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_2_4_3", vendingmachine.getDeposit()==5);
		assertTrue("1_2_4_3", checkDrink(COFFEE, 35, 0));
		assertTrue("1_2_4_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_2_4_3", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test59() throws Exception {
		System.out.println("Test case 59");
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_3", vendingmachine.getDeposit()==25);
		assertTrue("1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_3", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_1", vendingmachine.getDeposit()==30);
		assertTrue("1_3_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_3_1_1", vendingmachine.getDeposit()==0);
		assertTrue("1_3_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_3_1_1_1", vendingmachine.getDeposit()==10);
		assertTrue("1_3_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_3_1_1_1_1", vendingmachine.getDeposit()==110);
		assertTrue("1_3_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test60() throws Exception {
		System.out.println("Test case 60");
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_3_1_1_2", vendingmachine.getDeposit()==100);
		assertTrue("1_3_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_1_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test61() throws Exception {
		System.out.println("Test case 61");
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		assertTrue("1_3_2", vendingmachine.getDeposit()==0);
		assertTrue("1_3_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_3_2_1", vendingmachine.getDeposit()==10);
		assertTrue("1_3_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_3_2_1_1", vendingmachine.getDeposit()==110);
		assertTrue("1_3_2_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_2_1_1_1", vendingmachine.getDeposit()==115);
		assertTrue("1_3_2_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test62() throws Exception {
		System.out.println("Test case 62");
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_2_1_2", vendingmachine.getDeposit()==15);
		assertTrue("1_3_2_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test63() throws Exception {
		System.out.println("Test case 63");
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_3_2_2", vendingmachine.getDeposit()==100);
		assertTrue("1_3_2_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_2_2_1", vendingmachine.getDeposit()==105);
		assertTrue("1_3_2_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test64() throws Exception {
		System.out.println("Test case 64");
		vendingmachine.insertCoin(Coin.QUARTER);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_3_2_3", vendingmachine.getDeposit()==5);
		assertTrue("1_3_2_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_3_2_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_3_2_3", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test65() throws Exception {
		System.out.println("Test case 65");
		vendingmachine.insertCoin(Coin.NICKEL);
		assertTrue("1_4", vendingmachine.getDeposit()==5);
		assertTrue("1_4", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4", checkDrink(JUICE, 110, 1));
		assertTrue("1_4", checkDrink(SODA, 105, 1));
		vendingmachine.returnCoins();
		assertTrue("1_4_1", vendingmachine.getDeposit()==0);
		assertTrue("1_4_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DIME);
		assertTrue("1_4_1_1", vendingmachine.getDeposit()==10);
		assertTrue("1_4_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_4_1_1_1", vendingmachine.getDeposit()==110);
		assertTrue("1_4_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_1_1", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_4_1_1_1_1", vendingmachine.getDeposit()==135);
		assertTrue("1_4_1_1_1_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_1_1_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_1_1_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test66() throws Exception {
		System.out.println("Test case 66");
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.DIME);
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_4_1_1_2", vendingmachine.getDeposit()==35);
		assertTrue("1_4_1_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_1_2", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test67() throws Exception {
		System.out.println("Test case 67");
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.DOLLAR);
		assertTrue("1_4_1_2", vendingmachine.getDeposit()==100);
		assertTrue("1_4_1_2", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_2", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_2", checkDrink(SODA, 105, 1));
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_4_1_2_1", vendingmachine.getDeposit()==125);
		assertTrue("1_4_1_2_1", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_2_1", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_2_1", checkDrink(SODA, 105, 1));
	}

	@Test
	public void test68() throws Exception {
		System.out.println("Test case 68");
		vendingmachine.insertCoin(Coin.NICKEL);
		vendingmachine.returnCoins();
		vendingmachine.insertCoin(Coin.QUARTER);
		assertTrue("1_4_1_3", vendingmachine.getDeposit()==25);
		assertTrue("1_4_1_3", checkDrink(COFFEE, 35, 1));
		assertTrue("1_4_1_3", checkDrink(JUICE, 110, 1));
		assertTrue("1_4_1_3", checkDrink(SODA, 105, 1));
	}


		public static final String COFFEE = VendingMachine.COFFEE; 
		public static final String JUICE = VendingMachine.JUICE; 
		public static final String SODA = VendingMachine.SODA; 
		
		private boolean checkDrink(String drink, int price, int count) {
			if (drink.equalsIgnoreCase(COFFEE)) 
					return vendingmachine.getCoffee().getPrice()==price && vendingmachine.getCoffee().getCount()==count;
			if (drink.equalsIgnoreCase(JUICE)) 
					return vendingmachine.getJuice().getPrice()==price && vendingmachine.getJuice().getCount()==count;
			if (drink.equalsIgnoreCase(SODA)) 
					return vendingmachine.getSoda().getPrice()==price && vendingmachine.getSoda().getCount()==count;
			else
				return true;
		}
	
	
	
}
