//Test code generated by MISTA

import junit.framework.*;

public class CruiseControllerFSMTester_TC extends TestCase{

	private CruiseControllerFSM cruisecontrollerfsm;
	
	protected void setUp()  throws Exception {
		cruisecontrollerfsm = new CruiseControllerFSM();
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		cruisecontrollerfsm.engineOn();
		assertTrue("1_1", cruisecontrollerfsm.ACTIVE());
		cruisecontrollerfsm.engineOff();
		assertTrue("1_1_1", cruisecontrollerfsm.INACTIVE());
	}

	public void test2() throws Exception {
		System.out.println("Test case 2");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.brake();
		assertTrue("1_1_2", cruisecontrollerfsm.ACTIVE());
	}

	public void test3() throws Exception {
		System.out.println("Test case 3");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.accelerator();
		assertTrue("1_1_3", cruisecontrollerfsm.ACTIVE());
	}

	public void test4() throws Exception {
		System.out.println("Test case 4");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.on();
		assertTrue("1_1_4", cruisecontrollerfsm.CRUISING());
		cruisecontrollerfsm.engineOff();
		assertTrue("1_1_4_1", cruisecontrollerfsm.INACTIVE());
	}

	public void test5() throws Exception {
		System.out.println("Test case 5");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.on();
		cruisecontrollerfsm.brake();
		assertTrue("1_1_4_2", cruisecontrollerfsm.STANDBY());
		cruisecontrollerfsm.engineOff();
		assertTrue("1_1_4_2_1", cruisecontrollerfsm.INACTIVE());
	}

	public void test6() throws Exception {
		System.out.println("Test case 6");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.on();
		cruisecontrollerfsm.brake();
		cruisecontrollerfsm.resume();
		assertTrue("1_1_4_2_2", cruisecontrollerfsm.CRUISING());
	}

	public void test7() throws Exception {
		System.out.println("Test case 7");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.on();
		cruisecontrollerfsm.brake();
		cruisecontrollerfsm.on();
		assertTrue("1_1_4_2_3", cruisecontrollerfsm.CRUISING());
	}

	public void test8() throws Exception {
		System.out.println("Test case 8");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.on();
		cruisecontrollerfsm.accelerator();
		assertTrue("1_1_4_3", cruisecontrollerfsm.STANDBY());
	}

	public void test9() throws Exception {
		System.out.println("Test case 9");
		cruisecontrollerfsm.engineOn();
		cruisecontrollerfsm.on();
		cruisecontrollerfsm.off();
		assertTrue("1_1_4_4", cruisecontrollerfsm.STANDBY());
	}

}
