//Test code generated by MISTA

package test;

import cruisecontrol.*;
import org.junit.*;
import static org.junit.Assert.*;

public class ControllerTester_SC {

	private Controller controller;
	
	@Before
	public void setUp()  throws Exception {
		controller = new Controller();
	}
	
	@Test
	public void test1() throws Exception {
		System.out.println("Test case 1");
		controller.engineOn();
		assertTrue("1_1", controller.getControlState()==Controller.ACTIVE);
		assertTrue("1_1", ! (controller.getControlState()==Controller.INACTIVE));
		controller.engineOff();
		assertTrue("1_1_1", controller.getControlState()==Controller.INACTIVE);
		assertTrue("1_1_1", ! (controller.getControlState()==Controller.ACTIVE));
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
	}

	@Test
	public void test2() throws Exception {
		System.out.println("Test case 2");
		controller.engineOn();
		controller.on();
		assertTrue("1_1_2", controller.getControlState()==Controller.CRUISING);
		assertTrue("1_1_2", ! (controller.getControlState()==Controller.ACTIVE));
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.ENABLED);
		controller.accelerator();
		assertTrue("1_1_2_1", controller.getControlState()==Controller.STANDBY);
		assertTrue("1_1_2_1", ! (controller.getControlState()==Controller.CRUISING));
		assertTrue("", controller.getSpeedControl().getSpeedControlState()==SpeedControl.DISABLED);
	}

}
